"""TODO index generator and validator.

The problem this replaces
-------------------------
`TODO.md` grew to 2,555 lines holding three different kinds of writing at once:
closed post-mortems, open tasks, and design sketches. Status was free prose with
fourteen different phrasings, so nothing could be filtered; identifiers were
insert order, so there were two `item 19`s and an `item 0` appended after `item
18`; and no closed item ever left, so the file only grew.

The structure now
-----------------
    docs/todos/entries/*.md     open work — the source of truth, one file per item
    docs/decisions/ADR-*.md     closed work — the record of what was decided
    docs/design/*.md            long analysis, moved out of the entries
    TODO.md                     GENERATED index of the above
    docs/todos/id-map.md        GENERATED legacy-item → id map
    docs/decisions/README.md    GENERATED ADR index

Front matter carries the machine-readable part, so status and priority are fields
rather than sentences. Identifiers are minted once and never renumbered, because
seventeen items are referenced by number from code and docs.

Usage
-----
    uv run scripts/todo.py render     # regenerate TODO.md and the two indexes
    uv run scripts/todo.py check      # validate; non-zero exit on any error
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ENTRY_DIR = ROOT / "docs/todos/entries"
DECISION_DIR = ROOT / "docs/decisions"
TODO_PATH = ROOT / "TODO.md"
DECISION_INDEX = DECISION_DIR / "README.md"
ID_MAP = ROOT / "docs/todos/id-map.md"

GENERATED = "<!-- GENERATED by scripts/todo.py — edit the source files, not this file. -->"

ENTRY_STATUSES = ("open", "in-progress", "blocked", "parked", "done", "superseded")
ADR_STATUSES = ("accepted", "superseded", "proposed")
PRIORITIES = ("critical", "high", "medium", "low")
ACTIVE_STATUSES = ("open", "in-progress", "blocked")
RANK = {p: i for i, p in enumerate(PRIORITIES)}

ENTRY_ID_RE = re.compile(r"^YB-\d{3}[ab]?$")
ADR_ID_RE = re.compile(r"^ADR-\d{4}$")
FM_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)

REQUIRED_ENTRY = ("id", "title", "status", "priority", "area", "created",
                  "superseded_by", "related", "blocks", "blocked_by")
REQUIRED_ADR = ("id", "title", "status", "date", "area", "related")

DATE_FIELDS = ("created", "updated", "date")


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------


def load(path: Path) -> tuple[dict, str]:
    """Return (front matter, body). Raises on a missing or malformed block."""
    text = path.read_text()
    match = FM_RE.match(text)
    if not match:
        raise ValueError(f"{path.relative_to(ROOT)}: missing YAML front matter")
    try:
        meta = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError as exc:  # pragma: no cover - message shaping only
        raise ValueError(f"{path.relative_to(ROOT)}: bad front matter: {exc}") from exc
    if not isinstance(meta, dict):
        raise ValueError(f"{path.relative_to(ROOT)}: front matter is not a mapping")
    return meta, text[match.end():]


def load_all() -> tuple[list[dict], list[dict], dict[str, Path]]:
    """Load every entry and record; return (entries, records, id → path)."""
    entries, records, paths = [], [], {}
    for path in sorted(ENTRY_DIR.glob("*.md")):
        meta, body = load(path)
        meta["_path"], meta["_body"] = path, body
        entries.append(meta)
        if meta.get("id"):
            paths[str(meta["id"])] = path
    for path in sorted(DECISION_DIR.glob("ADR-*.md")):
        meta, body = load(path)
        meta["_path"], meta["_body"] = path, body
        records.append(meta)
        if meta.get("id"):
            paths[str(meta["id"])] = path
    return entries, records, paths


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def link(path: Path, text: str, base: Path | None = None) -> str:
    """Link to `path` as seen from `base` (the repo root by default)."""
    return f"[{text}]({Path(os.path.relpath(path, base or ROOT)).as_posix()})"


def cell(value: object) -> str:
    """Markdown table cells must not carry a raw pipe or newline."""
    return str(value).replace("|", "\\|").replace("\n", " ").strip() or "—"


def entry_row(entry: dict) -> str:
    path = entry["_path"]
    return (f"| {link(path, str(entry['id']))} | {cell(entry['title'])} "
            f"| {cell(entry['status'])} | {cell(entry.get('area', ''))} |")


def render_todo(entries: list[dict], records: list[dict]) -> str:
    active = [e for e in entries if e["status"] in ACTIVE_STATUSES]
    parked = [e for e in entries if e["status"] == "parked"]
    done = [e for e in entries if e["status"] == "done"]
    superseded = [e for e in entries if e["status"] == "superseded"]

    out = [
        GENERATED,
        "# TODO — SEA Platform",
        "",
        "Open work only. Each item is one file under `docs/todos/entries/` — that file "
        "is the source of truth and this index is generated from it.",
        "",
        f"**{len(active)} active · {len(parked)} parked · {len(superseded)} superseded "
        f"· {len(records)} closed records**",
        "",
        "| Where | What |",
        "|---|---|",
        "| `docs/todos/entries/` | open work, one file per item |",
        "| `docs/decisions/` | closed work — what was decided, with the evidence |",
        "| `docs/design/` | long analysis moved out of the entries |",
        "| `docs/todos/legacy-todo-v1.md` | the original single-file TODO, frozen |",
        "| `docs/todos/id-map.md` | legacy item number → current id |",
        "",
        "Regenerate with `uv run scripts/todo.py render`; validate with "
        "`uv run scripts/todo.py check`.",
        "",
    ]

    for priority in PRIORITIES:
        group = sorted((e for e in active if e["priority"] == priority),
                       key=lambda e: str(e["id"]))
        if not group:
            continue
        out += [f"## {priority.capitalize()}", "",
                "| ID | Item | Status | Area |", "|---|---|---|---|"]
        out += [entry_row(e) for e in group]
        out.append("")

    for title, group in (("Parked", parked), ("Superseded", superseded)):
        if not group:
            continue
        out += [f"## {title}", "",
                "| ID | Item | Status | Area |", "|---|---|---|---|"]
        out += [entry_row(e) for e in sorted(group, key=lambda e: str(e["id"]))]
        out.append("")

    if done:
        out += ["## Closed, retained for follow-ups", "",
                "| ID | Item | Record |", "|---|---|---|"]
        for entry in sorted(done, key=lambda e: str(e["id"])):
            record = entry.get("record")
            shown = link(ROOT / record, Path(record).stem) if record else "—"
            out.append(f"| {link(entry['_path'], str(entry['id']))} | "
                       f"{cell(entry['title'])} | {shown} |")
        out.append("")

    out += ["## Closed work — records", "",
            "| ADR | Decision | Date | Legacy |", "|---|---|---|---|"]
    for record in sorted(records, key=lambda r: str(r["id"])):
        out.append(f"| {link(record['_path'], str(record['id']))} | {cell(record['title'])} "
                   f"| {cell(record['date'])} | item {cell(record.get('legacy', '—'))} |")
    out += ["", "The index is generated from the entries — do not edit `TODO.md` by hand.", ""]
    return "\n".join(out)


def render_decision_index(records: list[dict]) -> str:
    out = [GENERATED, "# Architecture decision records", "",
           "Closed work from the TODO. Each record preserves its original write-up verbatim; "
           "the entry that tracked it no longer exists.", "",
           "| ADR | Decision | Date | Legacy item |", "|---|---|---|---|"]
    for record in sorted(records, key=lambda r: str(r["id"])):
        out.append(f"| {link(record['_path'], str(record['id']), DECISION_DIR)} | {cell(record['title'])} "
                   f"| {cell(record['date'])} | {cell(record.get('legacy', '—'))} |")
    out.append("")
    return "\n".join(out)


def _legacy_key(item: dict) -> tuple[int, str]:
    legacy = str(item.get("legacy", ""))
    digits = re.match(r"(\d+)", legacy)
    return (int(digits.group(1)) if digits else 999, legacy)


def render_id_map(entries: list[dict], records: list[dict]) -> str:
    out = [GENERATED, "# Legacy item map", "",
           "`TODO.md` v1 numbered items by insertion order, which produced two `item 19`s "
           "and an `item 0` after `item 18`. Identifiers are never renumbered now, so this "
           "map is the bridge for the references that still say `item N`.", "",
           "| Legacy | Title | Now | Kind |", "|---|---|---|---|"]
    for item in sorted(entries + records, key=_legacy_key):
        path = item["_path"]
        kind = "record" if str(item["id"]).startswith("ADR") else f"entry ({item['status']})"
        out.append(f"| {cell(item.get('legacy', '—'))} | {cell(item['title'])} "
                   f"| {link(path, str(item['id']), ID_MAP.parent)} | {kind} |")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------


def _check_date(value: object, where: str, errors: list[str]) -> None:
    try:
        dt.date.fromisoformat(str(value))
    except (TypeError, ValueError):
        errors.append(f"{where}: not an ISO date: {value!r}")


def _check_refs(meta: dict, key: str, known: set[str], where: str, errors: list[str]) -> None:
    value = meta.get(key) or []
    if not isinstance(value, list):
        errors.append(f"{where}: {key} must be a list, got {type(value).__name__}")
        return
    for ref in value:
        if ref not in known:
            errors.append(f"{where}: {key} references unknown id {ref!r}")


def validate(entries: list[dict], records: list[dict], paths: dict[str, Path],
             errors: list[str], warnings: list[str]) -> None:
    known = set(paths)

    for meta in entries:
        where = meta["_path"].relative_to(ROOT).as_posix()
        for field in REQUIRED_ENTRY:
            if field not in meta:
                errors.append(f"{where}: missing required field {field!r}")
        ident, status = str(meta.get("id", "")), str(meta.get("status", ""))
        if not ENTRY_ID_RE.match(ident):
            errors.append(f"{where}: bad id {ident!r} (expected YB-NNN)")
        if status not in ENTRY_STATUSES:
            errors.append(f"{where}: bad status {status!r} (one of {', '.join(ENTRY_STATUSES)})")
        if meta.get("priority") not in PRIORITIES:
            errors.append(f"{where}: bad priority {meta.get('priority')!r} "
                          f"(one of {', '.join(PRIORITIES)})")
        for field in DATE_FIELDS:
            if meta.get(field):
                _check_date(meta[field], f"{where}:{field}", errors)
        for key in ("related", "superseded_by", "blocks", "blocked_by"):
            _check_refs(meta, key, known, where, errors)
        for key in ("design", "record"):
            value = meta.get(key)
            if value and not (ROOT / str(value)).exists():
                errors.append(f"{where}: {key} points at a missing file: {value}")
        if status == "superseded" and not (meta.get("superseded_by") or []):
            errors.append(f"{where}: status superseded needs a non-empty superseded_by")
        if status == "done" and not meta.get("record"):
            errors.append(f"{where}: status done needs a record: pointing at its ADR")
        if status in ("open", "in-progress", "blocked") and meta.get("superseded_by"):
            errors.append(f"{where}: active item carries superseded_by")

    for meta in records:
        where = meta["_path"].relative_to(ROOT).as_posix()
        for field in REQUIRED_ADR:
            if field not in meta:
                errors.append(f"{where}: missing required field {field!r}")
        ident = str(meta.get("id", ""))
        if not ADR_ID_RE.match(ident):
            errors.append(f"{where}: bad id {ident!r} (expected ADR-NNNN)")
        if str(meta.get("status")) not in ADR_STATUSES:
            errors.append(f"{where}: bad status {meta.get('status')!r} "
                          f"(one of {', '.join(ADR_STATUSES)})")
        _check_date(meta.get("date"), f"{where}:date", errors)
        _check_refs(meta, "related", known, where, errors)

    # Duplicate identifiers would silently break every cross-reference.
    for label, items in (("entry", entries), ("record", records)):
        seen: dict[str, str] = {}
        for meta in items:
            ident = str(meta.get("id"))
            if ident in seen:
                errors.append(f"duplicate {label} id {ident}: "
                              f"{seen[ident]} and {meta['_path'].name}")
            seen[ident] = meta["_path"].name

    # Historical prose still says "item N"; new writing should use ids.
    for meta in entries:
        if meta["status"] not in ACTIVE_STATUSES:
            continue
        for number, line in enumerate(meta["_body"].splitlines(), start=1):
            if line.startswith("**Legacy "):  # quoted legacy metadata stays verbatim
                continue
            if re.search(r"\bitem[s]? \d", line):
                warnings.append(f"{meta['_path'].name}:{number}: says 'item N' — use the id "
                                f"(see docs/todos/id-map.md)")


def check_freshness(expected: dict[Path, str], errors: list[str]) -> None:
    for path, text in expected.items():
        rel = path.relative_to(ROOT).as_posix()
        if not path.exists():
            errors.append(f"{rel}: missing — run `uv run scripts/todo.py render`")
        elif path.read_text() != text:
            errors.append(f"{rel}: stale — run `uv run scripts/todo.py render`")


# --------------------------------------------------------------------------


def build() -> dict[Path, str]:
    entries, records, _ = load_all()
    return {TODO_PATH: render_todo(entries, records),
            DECISION_INDEX: render_decision_index(records),
            ID_MAP: render_id_map(entries, records)}


def cmd_render(_args: argparse.Namespace) -> int:
    for path, text in build().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT).as_posix()}")
    return 0


def cmd_check(_args: argparse.Namespace) -> int:
    entries, records, paths = load_all()
    errors: list[str] = []
    warnings: list[str] = []
    validate(entries, records, paths, errors, warnings)
    check_freshness(build(), errors)

    for warning in warnings:
        print(f"warning: {warning}")
    for error in errors:
        print(f"error: {error}")

    active = sum(1 for e in entries if e["status"] in ACTIVE_STATUSES)
    print(f"\n{len(entries)} entries ({active} active), {len(records)} records, "
          f"{len(warnings)} warning(s), {len(errors)} error(s)")
    return 1 if errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("render", help="regenerate TODO.md and the generated indexes")
    sub.add_parser("check", help="validate the entries and the generated files")
    args = parser.parse_args(argv)
    return {"render": cmd_render, "check": cmd_check}[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
